[package]
name = "pii-engineer-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pii-engineer-server"
path = "src/main.rs"

[dependencies]
pii-engineer-core = { path = "../pii-engineer-core" }

anyhow.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
once_cell.workspace = true
regex.workspace = true
tokio-stream.workspace = true
hf-hub.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
